env:
  browser: true
  es6: true
extends: [google, eslint:recommended, plugin:react/recommended]
globals:
  _: true
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  quotes: [0, "double"]
  linebreak-style: [0, "unix"]
